version: "3.9"
services:
  postgresql:
    image: "postgres"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d locallibrary-db -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=locallibrary-db

  web:
    build: .
    environment:
      - db_user=admin
      - db_pass=admin
      - db_name=locallibrary-db
      - DJANGO_DEBUG=True
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@locallibrary.org
      - DJANGO_SUPERUSER_PASSWORD=admin
    links:
      - postgresql
    depends_on:
      postgresql:
        condition: service_healthy
    ports:
      - 8000:8000